/**
 * Canonical routed-agent definition and renderer. The generator
 * produces one agent per route (the base) plus, for each normalized
 * effort level the model exposes, an additional `-<level>` agent
 * carrying the actual OpenCode variant key in its `variant:`
 * frontmatter field.
 *
 * Frontmatter contract (Rev 2):
 *   description: ...
 *   mode: subagent
 *   hidden: true
 *   model: provider/model
 *   variant: <actual-key>     # absent on the base agent
 *   permission:
 *     task:
 *       '*': deny
 */

export interface RoutedAgentRoute {
  hostName: string;
  providerId: string;
  modelId: string;
  baseTemplate: string;
}

export interface RoutedAgentVariant {
  /**
   * Normalized level name (e.g. "low", "medium", "high"). Used as
   * the agent file suffix and in the description. The actual SDK
   * variant key is the value of `variantKey`.
   */
  level: "low" | "medium" | "high";
  /** The model's actual OpenCode variant key, written to the `variant:` frontmatter field. */
  variantKey: string;
}

export interface CanonicalRoutedAgentDefinition {
  description: string;
  mode: "subagent";
  hidden: true;
  model: string;
  permission: { task: { "*": "deny" } };
  prompt: string;
  /** Absent on the base agent; present on `-low`/`-medium`/`-high` agents. */
  variant?: string;
}

export function buildCanonicalRoutedAgentDefinition(
  route: RoutedAgentRoute,
  variant?: RoutedAgentVariant,
): CanonicalRoutedAgentDefinition {
  const variantSuffix = variant !== undefined ? `, effort ${variant.level} -> variant ${variant.variantKey}` : " (host)";
  const variantFragment = variant !== undefined
    ? `\nThis agent is bound to the \`${variant.variantKey}\` OpenCode variant of \`${route.providerId}/${route.modelId}\` (normalized effort level: \`${variant.level}\`).`
    : "";
  const def: CanonicalRoutedAgentDefinition = {
    description: "Deterministic routed host for " + route.providerId + "/" + route.modelId + variantSuffix + ".",
    mode: "subagent",
    hidden: true,
    model: route.providerId + "/" + route.modelId,
    permission: { task: { "*": "deny" } },
    prompt:
      "# " + route.hostName + "\n\nRouted subagent bound to `" + route.providerId + "/" + route.modelId + "`." +
      variantFragment +
      "\nGenerated from baseTemplate \"" + route.baseTemplate + "\" via the pre-start disk agent generator.\n" +
      "Do not edit this file directly; rerun `npm run generate:model-routes` after editing config/model-routing/routes.json.\n",
  };
  if (variant !== undefined) def.variant = variant.variantKey;
  return def;
}

export function renderCanonicalRoutedAgentMarkdown(
  route: RoutedAgentRoute,
  variant?: RoutedAgentVariant,
): string {
  const def = buildCanonicalRoutedAgentDefinition(route, variant);
  const variantLine = def.variant !== undefined ? `variant: ${def.variant}\n` : "";
  return "---\ndescription: " + def.description + "\nmode: subagent\nhidden: true\nmodel: " + def.model + "\n" + variantLine + "permission:\n  task:\n    '*': deny\n---\n\n" + def.prompt;
}

export function compareResolvedAgentDefinition(actual: any, expected: CanonicalRoutedAgentDefinition): readonly string[] {
  const diffs: string[] = [];
  if (!actual || typeof actual !== "object") {
    diffs.push("root");
    return diffs;
  }

  if (actual.mode !== expected.mode) diffs.push("mode");
  if (actual.hidden !== expected.hidden) diffs.push("hidden");
  if (actual.model !== expected.model) diffs.push("model");
  if (actual.description !== expected.description) diffs.push("description");

  const allowedKeys = new Set(["mode", "hidden", "model", "description", "permission", "prompt", "name", "variant"]);
  for (const key of Object.keys(actual)) {
    if (!allowedKeys.has(key)) {
       if (["disable", "tools", "maxSteps", "temperature", "top_p", "color"].includes(key)) {
          diffs.push(key);
       }
    }
  }

  return diffs;
}
