export interface RoutedAgentRoute {
  hostName: string;
  providerId: string;
  modelId: string;
  baseTemplate: string;
}

export interface CanonicalRoutedAgentDefinition {
  description: string;
  mode: "subagent";
  hidden: true;
  model: string;
  permission: { task: { "*": "deny" } };
  prompt: string;
}

export function buildCanonicalRoutedAgentDefinition(route: RoutedAgentRoute): CanonicalRoutedAgentDefinition {
  return {
    description: "Deterministic routed host for " + route.providerId + "/" + route.modelId + " (host).",
    mode: "subagent",
    hidden: true,
    model: route.providerId + "/" + route.modelId,
    permission: { task: { "*": "deny" } },
    prompt: "# " + route.hostName + "\n\nRouted subagent bound to `" + route.providerId + "/" + route.modelId + "`.\nGenerated from baseTemplate \"" + route.baseTemplate + "\" via the pre-start disk agent generator.\nDo not edit this file directly; rerun `npm run generate:model-routes` after editing config/model-routing/routes.json.\n"
  };
}

export function renderCanonicalRoutedAgentMarkdown(route: RoutedAgentRoute): string {
  const def = buildCanonicalRoutedAgentDefinition(route);
  return "---\ndescription: " + def.description + "\nmode: subagent\nhidden: true\nmodel: " + def.model + "\npermission:\n  task:\n    '*': deny\n---\n\n" + def.prompt;
}

export function compareResolvedAgentDefinition(actual: any, expected: CanonicalRoutedAgentDefinition): readonly string[] {
  const diffs: string[] = [];
  if (!actual || typeof actual !== "object") {
    diffs.push("root");
    return diffs;
  }
  
  if (actual.mode !== expected.mode) diffs.push("mode");
  if (actual.hidden !== expected.hidden) diffs.push("hidden");
  if (actual.model !== expected.model) diffs.push("model");
  if (actual.description !== expected.description) diffs.push("description");

  const allowedKeys = new Set(["mode", "hidden", "model", "description", "permission", "prompt", "name"]);
  for (const key of Object.keys(actual)) {
    if (!allowedKeys.has(key)) {
       if (["disable", "tools", "maxSteps", "temperature", "top_p", "color"].includes(key)) {
          diffs.push(key);
       }
    }
  }

  return diffs;
}
